	AREA RESET,CODE
	ENTRY
	LDR R0,=VAL
	MOV R1,#5 ;TOTAL 5 NUMBERS
	MOV R2,#0 ;RESULT SMALLEST
	LDR R2,[R0],#4 ;FIRST NUMBER
LABEL1	LDR R3,[R0] ;NEXT NUMBER
	CMP R2,R3
	BLT LABEL
	MOV R2,R3
LABEL
	ADD R0,#4
	SUB R1,#1
	CMP R1,#0
	BNE LABEL1	
	LDR R0,=RES
	STR R2,[R0]
STOP B STOP
VAL DCD &57,&2,&9,&10,&7
	AREA MEMORY,DATA
RES SPACE 4	
	END